import {
    TrendingUp,
    Book,
    Trophy,
    Target,
} from 'lucide-react';

export const campusStats = [
    { value: '150+', label: 'Active Communities' },
    { value: '22k+', label: 'Student Gamers' },
    { value: '3,600+', label: 'Yearly Events' },
];

export const campusPillars = [
    {
        title: 'Community Management',
        description:
            'We monitor the health of 150+ MSL Communities. This involves enforcing community guidelines, conflict resolution, and ensuring every student leader has the resources to run their local hub effectively.',
        Icon: Target,
    },
    {
        title: 'Tournament Operations',
        description:
            "We execute Campus Tournaments, a circuit of Online and Onsite events. Our team handles bracket management, ruleset enforcement, and disputes to ensure fair play across Luzon, Visayas, and Mindanao.",
        Icon: Trophy,
    },
    {
        title: 'Student Development',
        description:
            "We don't just build gamers; we build leaders. Through our mentorship programs, we train Community Heads in event management, leadership, and professional communication.",
        Icon: Book,
    },
];

export const accreditationBenefits = [
    'Official Recognition',
    'Monthly Diamond Support',
    'Tournament Kits',
];

export const campusPrograms = [
    {
        title: 'Ongoing Campus Tournaments',
        description:
            "Compete for school pride in our official competitive circuits. Whether it's the Monthly Online Tournaments for remote play or the Onsite Events held within campus premises.",
        action: 'Find Your Tournament',
        href: '/Events',
        Icon: Trophy,
    },
    {
        title: 'Leadership Training',
        description:
            'Workshops, seminars, and mentorship programs designed to mold student gamers into capable, professional community leaders.',
        action: 'View Programs',
        href: '#campus-pillars',
        Icon: TrendingUp,
    },
];

export const campusJourney = [
    {
        number: '01',
        title: 'Application',
        description: 'Submit requirements and pass the interview.',
        accent: 'border-white/30 text-white',
    },
    {
        number: '02',
        title: 'Tier C / B',
        description: 'Probationary to Development phase.',
        accent: 'border-blue-500 text-blue-400',
    },
    {
        number: '03',
        title: 'Tier A',
        description: 'High performance & consistent events.',
        accent: 'border-purple-500 text-purple-400',
    },
    {
        number: '04',
        title: 'Super School',
        description: 'Top-tier performance. Max funding & exclusive perks.',
        accent: 'border-amber-400 text-amber-300',
    },
];

export const departmentHead = {
    name: 'Mary Clarence S. Pasco',
    role: 'Department Head',
    image: '/profile-background.jpg',
    quote:
        "We are the voice and the face of the MSL network. Our mission is to tell the stories of our student leaders, amplify the excitement of our tournaments, and create content that resonates with the collegiate gaming community.",
};

export const regionalAdmins = [
    { region: 'NCR-North', name: 'Jamie Rivera' },
    { region: 'NCR-South', name: 'Mark Corpus' },
    { region: 'South Luzon', name: 'Leo Valdez' },
    { region: 'North Luzon', name: 'Nina Santos' },
    { region: 'Central Luzon', name: 'Kenji Tanaka' },
    { region: 'Bicol Region', name: 'Ria Jose' },
    { region: 'West Visayas', name: 'Jamie Rivera' },
    { region: 'Central Visayas', name: 'Mark Corpus' },
    { region: 'East Visayas', name: 'Leo Valdez' },
    { region: 'North Mindanao', name: 'Nina Santos' },
    { region: 'South Mindanao', name: 'Kenji Tanaka' },
    { region: 'West Mindanao', name: 'Ria Jose' },
    { region: 'BARMM', name: 'Jamie Rivera' },
];

export const campusCommunities = [
    {
        school: 'Ateneo de Davao University',
        community: 'AdDU - Blue Knights',
        region: 'Mindanao',
        tier: 'Tier B',
        members: 600,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Bulacan State University',
        community: 'BulSU - Student Community',
        region: 'North/Central Luzon',
        tier: 'Tier C',
        members: 350,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Central Philippine University',
        community: 'CPU - Golden Lions',
        region: 'Visayas',
        tier: 'Tier C',
        members: 500,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'National University',
        community: 'NU - Bulldogs Esports',
        region: 'NCR',
        tier: 'Tier A',
        members: 820,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Baguio',
        community: 'UB - Cardinals Gaming',
        region: 'North/Central Luzon',
        tier: 'Tier B',
        members: 410,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of San Carlos',
        community: 'USC - Warriors',
        region: 'Visayas',
        tier: 'Tier A',
        members: 730,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Adamson University',
        community: 'AdU - Falcons Esports',
        region: 'NCR',
        tier: 'Tier B',
        members: 520,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Arellano University',
        community: 'AU - Chiefs Gaming',
        region: 'NCR',
        tier: 'Tier C',
        members: 290,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'De La Salle University',
        community: 'DLSU - Animo Esports',
        region: 'NCR',
        tier: 'Tier A',
        members: 940,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Far Eastern University',
        community: 'FEU - Tamaraws Gaming',
        region: 'NCR',
        tier: 'Tier B',
        members: 610,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Mapua University',
        community: 'Mapua - Cardinals Esports',
        region: 'NCR',
        tier: 'Tier B',
        members: 455,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Polytechnic University of the Philippines',
        community: 'PUP - Iskolar Gaming',
        region: 'NCR',
        tier: 'Tier A',
        members: 880,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Technological Institute of the Philippines',
        community: 'TIP - Engineers Esports',
        region: 'NCR',
        tier: 'Tier C',
        members: 365,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of the East',
        community: 'UE - Warriors Gaming',
        region: 'NCR',
        tier: 'Tier B',
        members: 505,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Santo Tomas',
        community: 'UST - Tigers Esports',
        region: 'NCR',
        tier: 'Tier A',
        members: 990,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Pamantasan ng Lungsod ng Maynila',
        community: 'PLM - Haribons Gaming',
        region: 'NCR',
        tier: 'Tier C',
        members: 420,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Angeles University Foundation',
        community: 'AUF - Great Danes Esports',
        region: 'North/Central Luzon',
        tier: 'Tier C',
        members: 315,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Bataan Peninsula State University',
        community: 'BPSU - Peninsula Gamers',
        region: 'North/Central Luzon',
        tier: 'Tier B',
        members: 470,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Cagayan State University',
        community: 'CSU - Eagles Esports',
        region: 'North/Central Luzon',
        tier: 'Tier C',
        members: 340,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Don Honorio Ventura State University',
        community: 'DHVSU - Honorians Gaming',
        region: 'North/Central Luzon',
        tier: 'Tier B',
        members: 510,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Holy Angel University',
        community: 'HAU - Angelites Esports',
        region: 'North/Central Luzon',
        tier: 'Tier B',
        members: 545,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Isabela State University',
        community: 'ISU - Falcons Gaming',
        region: 'North/Central Luzon',
        tier: 'Tier C',
        members: 330,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Nueva Ecija University of Science and Technology',
        community: 'NEUST - Phoenix Esports',
        region: 'North/Central Luzon',
        tier: 'Tier C',
        members: 395,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Pangasinan State University',
        community: 'PSU - Golden Lions Gaming',
        region: 'North/Central Luzon',
        tier: 'Tier B',
        members: 485,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Saint Louis University',
        community: 'SLU - Navigators Esports',
        region: 'North/Central Luzon',
        tier: 'Tier A',
        members: 710,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Tarlac State University',
        community: 'TSU - Foxes Gaming',
        region: 'North/Central Luzon',
        tier: 'Tier B',
        members: 560,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Batangas State University',
        community: 'BatStateU - Red Spartans Esports',
        region: 'South Luzon',
        tier: 'Tier A',
        members: 835,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Cavite State University',
        community: 'CvSU - Hornets Gaming',
        region: 'South Luzon',
        tier: 'Tier B',
        members: 625,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'De La Salle Lipa',
        community: 'DLSL - Blazers Esports',
        region: 'South Luzon',
        tier: 'Tier C',
        members: 305,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Laguna State Polytechnic University',
        community: 'LSPU - Lakers Gaming',
        region: 'South Luzon',
        tier: 'Tier B',
        members: 430,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Lyceum of the Philippines University Batangas',
        community: 'LPU-B - Pirates Esports',
        region: 'South Luzon',
        tier: 'Tier C',
        members: 360,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Manuel S. Enverga University Foundation',
        community: 'MSEUF - Wildcats Gaming',
        region: 'South Luzon',
        tier: 'Tier C',
        members: 275,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Batangas',
        community: 'UBatangas - Brahmans Esports',
        region: 'South Luzon',
        tier: 'Tier B',
        members: 455,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Perpetual Help System DALTA',
        community: 'Perpetual - Altas Gaming',
        region: 'South Luzon',
        tier: 'Tier C',
        members: 385,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Ateneo de Naga University',
        community: 'AdNU - Golden Knights Esports',
        region: 'South Luzon',
        tier: 'Tier B',
        members: 525,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Bicol University',
        community: 'BU - Trailblazers Gaming',
        region: 'South Luzon',
        tier: 'Tier A',
        members: 765,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Aklan State University',
        community: 'ASU - Falcons Esports',
        region: 'Visayas',
        tier: 'Tier C',
        members: 285,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Cebu Institute of Technology - University',
        community: 'CIT-U - Wildcats Gaming',
        region: 'Visayas',
        tier: 'Tier B',
        members: 590,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Cebu Normal University',
        community: 'CNU - Normalites Esports',
        region: 'Visayas',
        tier: 'Tier C',
        members: 315,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Negros Oriental State University',
        community: 'NORSU - Wolves Gaming',
        region: 'Visayas',
        tier: 'Tier B',
        members: 445,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Silliman University',
        community: 'SU - Stallions Esports',
        region: 'Visayas',
        tier: 'Tier A',
        members: 705,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Antique',
        community: 'UA - Warriors Gaming',
        region: 'Visayas',
        tier: 'Tier C',
        members: 260,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Cebu',
        community: 'UC - Webmasters Esports',
        region: 'Visayas',
        tier: 'Tier B',
        members: 650,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Iloilo',
        community: 'UI - Wildcats Gaming',
        region: 'Visayas',
        tier: 'Tier C',
        members: 335,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Negros Occidental - Recoletos',
        community: 'UNO-R - Rams Esports',
        region: 'Visayas',
        tier: 'Tier B',
        members: 405,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'West Visayas State University',
        community: 'WVSU - Taga-West Gaming',
        region: 'Visayas',
        tier: 'Tier A',
        members: 790,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Ateneo de Zamboanga University',
        community: 'AdZU - Azul Aguilas Esports',
        region: 'Mindanao',
        tier: 'Tier B',
        members: 540,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Bukidnon State University',
        community: 'BukSU - Highlanders Gaming',
        region: 'Mindanao',
        tier: 'Tier C',
        members: 320,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Caraga State University',
        community: 'CSU - Gold Panthers Esports',
        region: 'Mindanao',
        tier: 'Tier B',
        members: 480,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Central Mindanao University',
        community: 'CMU - Musuan Gaming',
        region: 'Mindanao',
        tier: 'Tier B',
        members: 515,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Mindanao State University - Iligan Institute of Technology',
        community: 'MSU-IIT - Titans Esports',
        region: 'Mindanao',
        tier: 'Tier A',
        members: 820,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Notre Dame of Dadiangas University',
        community: 'NDDU - Marist Gaming',
        region: 'Mindanao',
        tier: 'Tier C',
        members: 300,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Mindanao',
        community: 'UM - Wildcats Esports',
        region: 'Mindanao',
        tier: 'Tier A',
        members: 860,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of Science and Technology of Southern Philippines',
        community: 'USTP - Trailblazers Gaming',
        region: 'Mindanao',
        tier: 'Tier B',
        members: 610,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Xavier University - Ateneo de Cagayan',
        community: 'XU - Crusaders Esports',
        region: 'Mindanao',
        tier: 'Tier B',
        members: 575,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Zamboanga Peninsula Polytechnic State University',
        community: 'ZPPSU - Builders Gaming',
        region: 'Mindanao',
        tier: 'Tier C',
        members: 345,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Colegio de San Juan de Letran',
        community: 'Letran - Knights Esports',
        region: 'NCR',
        tier: 'Tier B',
        members: 500,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'San Beda University',
        community: 'SBU - Red Lions Gaming',
        region: 'NCR',
        tier: 'Tier B',
        members: 535,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'Southern Luzon State University',
        community: 'SLSU - Kingfishers Esports',
        region: 'South Luzon',
        tier: 'Tier C',
        members: 370,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
    {
        school: 'University of the Philippines Los Banos',
        community: 'UPLB - Isko Gaming',
        region: 'South Luzon',
        tier: 'Tier A',
        members: 745,
        image: '/msl campus icon image.png',
        href: '#accreditation',
    },
];
