export const studentProfileData = {
    playerName: 'Jairuz Paulo Saure',
    playerUsername: '@urjaijai',
    playerGender: 'male',
    isVerified: true,
    playerLevel: 'LVL 142',
    profileBackground: '/profile-background.jpg',
    featuredIcon: '/Featured%20icon.png',
    schoolName: 'Southville International School and Colleges',
    yearLevel: 'Masters',
    courseName: 'Master in Information Technology',
    profileEditLabel: 'Edit Profile',
    syncNotice: 'Please note that real-time updates are subject to provider synchronization schedules.',
    editableProfile: {
        contactNo: '09123456789',
        facebookLink: 'https://facebook.com/urjaijai',
        email: 'jairuz.saure@university.edu.ph',
        squadAbbreviation: 'SYS',
    },
    coverPhotos: [
        { id: 'cover-1', image: '/profile-background.jpg', status: 'active' },
        { id: 'cover-2', image: '/profile-background.jpg', status: 'selected' },
        { id: 'cover-3', image: '/profile-background.jpg', status: 'default' },
        { id: 'cover-4', image: '/profile-background.jpg', status: 'default' },
        { id: 'cover-5', image: '/profile-background.jpg', status: 'default' },
        { id: 'cover-6', image: '/profile-background.jpg', status: 'default' },
        { id: 'cover-7', image: '/profile-background.jpg', status: 'default' },
        { id: 'cover-8', image: '/profile-background.jpg', status: 'default' },
    ],
    playerInformation: {
        ign: '╰‿╯',
        uid: '608446759',
        server: 'PH Server',
        squad: 'System Override',
        role: 'Jungler',
        rankImage: '/rank image.png',
    },
    mostUsedHero: {
        name: 'Claude',
        image: '/most used hero.png',
        seasonLabel: 'Season 40',
        stats: {
            matches: '100',
            winRate: '63.6%',
        },
    },
    header: {
        textFlex: '3.25 1 0%',
        rowMaxWidth: 1120,
        paddingX: 40,
        paddingY: 24,
        gap: 12,
    },
    heroList: [
        { id: 2, name: 'Claude', image: '/most used hero.png', matches: '6 Matches', wr: '66.7% WR' },
        { id: 3, name: 'Claude', image: '/most used hero.png', matches: '6 Matches', wr: '66.7% WR' },
        { id: 4, name: 'Claude', image: '/most used hero.png', matches: '6 Matches', wr: '66.7% WR' },
        { id: 5, name: 'Claude', image: '/most used hero.png', matches: '6 Matches', wr: '66.7% WR' },
        { id: 6, name: 'Claude', image: '/most used hero.png', matches: '6 Matches', wr: '66.7% WR' },
    ],
    stats: [
        { title: 'ALL MATCHES', value: '2,510', icon: 'gamepad' },
        { title: 'WIN COUNT', value: '1,284', icon: 'trophy' },
        { title: 'PLAY TIME', value: '482h', icon: 'clock' },
        { title: 'WIN STREAK', value: '20', icon: 'fire' },
        { title: 'MVP COUNT', value: '341', icon: 'award' },
    ],
    poster: {
        campus: 'MSL Campus',
        schedule: '04/10/26 - FRIDAY - 8PM',
        title: 'STREAMER NIGHT',
        subtitle: "GUESS THE STREAMER'S FAVORITE HERO",
    },
};
